package com.yida.work.entity;

public class MenuT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_URL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_PID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_HEADING
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private Integer menuHeading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_TRANSLATE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuTranslate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_PARAMS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_ALERT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuAlert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_LABEL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_ICON
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String menuIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menu_t.MENU_SORT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private Long menuSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_ID
     *
     * @return the value of yida_menu_t.MENU_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_ID
     *
     * @param menuId the value for yida_menu_t.MENU_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_NAME
     *
     * @return the value of yida_menu_t.MENU_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_NAME
     *
     * @param menuName the value for yida_menu_t.MENU_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_URL
     *
     * @return the value of yida_menu_t.MENU_URL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_URL
     *
     * @param menuUrl the value for yida_menu_t.MENU_URL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_PID
     *
     * @return the value of yida_menu_t.MENU_PID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuPid() {
        return menuPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_PID
     *
     * @param menuPid the value for yida_menu_t.MENU_PID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuPid(String menuPid) {
        this.menuPid = menuPid == null ? null : menuPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_HEADING
     *
     * @return the value of yida_menu_t.MENU_HEADING
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public Integer getMenuHeading() {
        return menuHeading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_HEADING
     *
     * @param menuHeading the value for yida_menu_t.MENU_HEADING
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuHeading(Integer menuHeading) {
        this.menuHeading = menuHeading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_TRANSLATE
     *
     * @return the value of yida_menu_t.MENU_TRANSLATE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuTranslate() {
        return menuTranslate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_TRANSLATE
     *
     * @param menuTranslate the value for yida_menu_t.MENU_TRANSLATE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuTranslate(String menuTranslate) {
        this.menuTranslate = menuTranslate == null ? null : menuTranslate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_PARAMS
     *
     * @return the value of yida_menu_t.MENU_PARAMS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuParams() {
        return menuParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_PARAMS
     *
     * @param menuParams the value for yida_menu_t.MENU_PARAMS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuParams(String menuParams) {
        this.menuParams = menuParams == null ? null : menuParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_ALERT
     *
     * @return the value of yida_menu_t.MENU_ALERT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuAlert() {
        return menuAlert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_ALERT
     *
     * @param menuAlert the value for yida_menu_t.MENU_ALERT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuAlert(String menuAlert) {
        this.menuAlert = menuAlert == null ? null : menuAlert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_LABEL
     *
     * @return the value of yida_menu_t.MENU_LABEL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuLabel() {
        return menuLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_LABEL
     *
     * @param menuLabel the value for yida_menu_t.MENU_LABEL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuLabel(String menuLabel) {
        this.menuLabel = menuLabel == null ? null : menuLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_ICON
     *
     * @return the value of yida_menu_t.MENU_ICON
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_ICON
     *
     * @param menuIcon the value for yida_menu_t.MENU_ICON
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon == null ? null : menuIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menu_t.MENU_SORT
     *
     * @return the value of yida_menu_t.MENU_SORT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public Long getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menu_t.MENU_SORT
     *
     * @param menuSort the value for yida_menu_t.MENU_SORT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setMenuSort(Long menuSort) {
        this.menuSort = menuSort;
    }
}