package com.yida.work.entity;

public class MenuPrivR {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menupriv_r.ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_menupriv_r.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menupriv_r.ID
     *
     * @return the value of yida_menupriv_r.ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menupriv_r.ID
     *
     * @param id the value for yida_menupriv_r.ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_menupriv_r.PRIVILEGE_ID
     *
     * @return the value of yida_menupriv_r.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_menupriv_r.PRIVILEGE_ID
     *
     * @param privilegeId the value for yida_menupriv_r.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setPrivilegeId(String privilegeId) {
        this.privilegeId = privilegeId == null ? null : privilegeId.trim();
    }
}