package com.yida.work.entity;

import java.util.Date;

public class PrivilegeT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String privilegeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.PRIVILEGE_TYPE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String privilegeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.PRIVILEGE_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String privilegeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.DESCRIPTION
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.PRIVILEGE_STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String privilegeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String lastModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_privilege_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private Date lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.PRIVILEGE_ID
     *
     * @return the value of yida_privilege_t.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.PRIVILEGE_ID
     *
     * @param privilegeId the value for yida_privilege_t.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setPrivilegeId(String privilegeId) {
        this.privilegeId = privilegeId == null ? null : privilegeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.PRIVILEGE_TYPE
     *
     * @return the value of yida_privilege_t.PRIVILEGE_TYPE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getPrivilegeType() {
        return privilegeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.PRIVILEGE_TYPE
     *
     * @param privilegeType the value for yida_privilege_t.PRIVILEGE_TYPE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setPrivilegeType(String privilegeType) {
        this.privilegeType = privilegeType == null ? null : privilegeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.PRIVILEGE_NAME
     *
     * @return the value of yida_privilege_t.PRIVILEGE_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.PRIVILEGE_NAME
     *
     * @param privilegeName the value for yida_privilege_t.PRIVILEGE_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName == null ? null : privilegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.DESCRIPTION
     *
     * @return the value of yida_privilege_t.DESCRIPTION
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.DESCRIPTION
     *
     * @param description the value for yida_privilege_t.DESCRIPTION
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.PRIVILEGE_STATUS
     *
     * @return the value of yida_privilege_t.PRIVILEGE_STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getPrivilegeStatus() {
        return privilegeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.PRIVILEGE_STATUS
     *
     * @param privilegeStatus the value for yida_privilege_t.PRIVILEGE_STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setPrivilegeStatus(String privilegeStatus) {
        this.privilegeStatus = privilegeStatus == null ? null : privilegeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.CREATER
     *
     * @return the value of yida_privilege_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.CREATER
     *
     * @param creater the value for yida_privilege_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.CREATE_TIME
     *
     * @return the value of yida_privilege_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.CREATE_TIME
     *
     * @param createTime the value for yida_privilege_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.LAST_MODIFIER
     *
     * @return the value of yida_privilege_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.LAST_MODIFIER
     *
     * @param lastModifier the value for yida_privilege_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_privilege_t.LAST_MODIFY_TIME
     *
     * @return the value of yida_privilege_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_privilege_t.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for yida_privilege_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}