package com.yida.work.entity;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_role_t.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_role_t.ROLE_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_role_t.ROLE_DESCRIPTION
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String roleDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_role_t.ROLE_STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String roleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_role_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_role_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_role_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String lastModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_role_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private Date lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_role_t.ROLE_ID
     *
     * @return the value of yida_role_t.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_role_t.ROLE_ID
     *
     * @param roleId the value for yida_role_t.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_role_t.ROLE_NAME
     *
     * @return the value of yida_role_t.ROLE_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_role_t.ROLE_NAME
     *
     * @param roleName the value for yida_role_t.ROLE_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_role_t.ROLE_DESCRIPTION
     *
     * @return the value of yida_role_t.ROLE_DESCRIPTION
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_role_t.ROLE_DESCRIPTION
     *
     * @param roleDescription the value for yida_role_t.ROLE_DESCRIPTION
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_role_t.ROLE_STATUS
     *
     * @return the value of yida_role_t.ROLE_STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getRoleStatus() {
        return roleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_role_t.ROLE_STATUS
     *
     * @param roleStatus the value for yida_role_t.ROLE_STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setRoleStatus(String roleStatus) {
        this.roleStatus = roleStatus == null ? null : roleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_role_t.CREATER
     *
     * @return the value of yida_role_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_role_t.CREATER
     *
     * @param creater the value for yida_role_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_role_t.CREATE_TIME
     *
     * @return the value of yida_role_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_role_t.CREATE_TIME
     *
     * @param createTime the value for yida_role_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_role_t.LAST_MODIFIER
     *
     * @return the value of yida_role_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_role_t.LAST_MODIFIER
     *
     * @param lastModifier the value for yida_role_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_role_t.LAST_MODIFY_TIME
     *
     * @return the value of yida_role_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_role_t.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for yida_role_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}