package com.yida.work.entity;

public class RolePrivilegeR {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_roleprivilege_r.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_roleprivilege_r.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_roleprivilege_r.ROLE_ID
     *
     * @return the value of yida_roleprivilege_r.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_roleprivilege_r.ROLE_ID
     *
     * @param roleId the value for yida_roleprivilege_r.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_roleprivilege_r.PRIVILEGE_ID
     *
     * @return the value of yida_roleprivilege_r.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_roleprivilege_r.PRIVILEGE_ID
     *
     * @param privilegeId the value for yida_roleprivilege_r.PRIVILEGE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setPrivilegeId(String privilegeId) {
        this.privilegeId = privilegeId == null ? null : privilegeId.trim();
    }
}