package com.yida.work.entity;

public class UserRoleR {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_userrole_r.ACCOUNT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_userrole_r.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_userrole_r.ACCOUNT
     *
     * @return the value of yida_userrole_r.ACCOUNT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_userrole_r.ACCOUNT
     *
     * @param account the value for yida_userrole_r.ACCOUNT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_userrole_r.ROLE_ID
     *
     * @return the value of yida_userrole_r.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_userrole_r.ROLE_ID
     *
     * @param roleId the value for yida_userrole_r.ROLE_ID
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}