package com.yida.work.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.ACCOUNT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.PASSWORD
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.REAL_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.NICK_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.IMG_PATH
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.PHONE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.EMAIL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private String lastModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yida_user_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    private Date lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.ACCOUNT
     *
     * @return the value of yida_user_t.ACCOUNT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.ACCOUNT
     *
     * @param account the value for yida_user_t.ACCOUNT
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.PASSWORD
     *
     * @return the value of yida_user_t.PASSWORD
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.PASSWORD
     *
     * @param password the value for yida_user_t.PASSWORD
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.REAL_NAME
     *
     * @return the value of yida_user_t.REAL_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.REAL_NAME
     *
     * @param realName the value for yida_user_t.REAL_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.NICK_NAME
     *
     * @return the value of yida_user_t.NICK_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.NICK_NAME
     *
     * @param nickName the value for yida_user_t.NICK_NAME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.IMG_PATH
     *
     * @return the value of yida_user_t.IMG_PATH
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.IMG_PATH
     *
     * @param imgPath the value for yida_user_t.IMG_PATH
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.PHONE
     *
     * @return the value of yida_user_t.PHONE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.PHONE
     *
     * @param phone the value for yida_user_t.PHONE
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.EMAIL
     *
     * @return the value of yida_user_t.EMAIL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.EMAIL
     *
     * @param email the value for yida_user_t.EMAIL
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.STATUS
     *
     * @return the value of yida_user_t.STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.STATUS
     *
     * @param status the value for yida_user_t.STATUS
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.CREATER
     *
     * @return the value of yida_user_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.CREATER
     *
     * @param creater the value for yida_user_t.CREATER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.CREATE_TIME
     *
     * @return the value of yida_user_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.CREATE_TIME
     *
     * @param createTime the value for yida_user_t.CREATE_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.LAST_MODIFIER
     *
     * @return the value of yida_user_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.LAST_MODIFIER
     *
     * @param lastModifier the value for yida_user_t.LAST_MODIFIER
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yida_user_t.LAST_MODIFY_TIME
     *
     * @return the value of yida_user_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yida_user_t.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for yida_user_t.LAST_MODIFY_TIME
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}