package com.yida.work.dao;

import com.yida.work.entity.MenuPrivR;

public interface MenuPrivRMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_menupriv_r
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insert(MenuPrivR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_menupriv_r
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insertSelective(MenuPrivR record);
}