package com.yida.work.dao;

import com.yida.work.entity.MenuT;

public interface MenuTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_menu_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_menu_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insert(MenuT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_menu_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insertSelective(MenuT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_menu_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    MenuT selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_menu_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int updateByPrimaryKeySelective(MenuT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_menu_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int updateByPrimaryKey(MenuT record);
}