package com.yida.work.dao;

import com.yida.work.entity.PrivilegeT;

public interface PrivilegeTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_privilege_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int deleteByPrimaryKey(String privilegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_privilege_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insert(PrivilegeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_privilege_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insertSelective(PrivilegeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_privilege_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    PrivilegeT selectByPrimaryKey(String privilegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_privilege_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int updateByPrimaryKeySelective(PrivilegeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_privilege_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int updateByPrimaryKey(PrivilegeT record);
}