package com.yida.work.dao;

import com.yida.work.entity.RolePrivilegeR;

public interface RolePrivilegeRMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_roleprivilege_r
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insert(RolePrivilegeR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_roleprivilege_r
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insertSelective(RolePrivilegeR record);
}