package com.yida.work.dao;

import com.yida.work.entity.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_role_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_role_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_role_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_role_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    Role selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_role_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_role_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int updateByPrimaryKey(Role record);
}