package com.yida.work.dao;

import com.yida.work.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_user_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int deleteByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_user_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_user_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_user_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    User selectByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_user_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_user_t
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int updateByPrimaryKey(User record);
}