package com.yida.work.dao;

import com.yida.work.entity.UserRoleR;

public interface UserRoleRMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_userrole_r
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insert(UserRoleR record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yida_userrole_r
     *
     * @mbg.generated Thu Jan 31 14:46:30 CST 2019
     */
    int insertSelective(UserRoleR record);
}